---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palworld-k8s.fullname" . }}
  labels:
    {{- include "palworld-k8s.labels" . | nindent 4 }}
data:
  TZ: "{{ .Values.tz }}"
  PLAYERS: "{{ .Values.gameServer.players | int }}"
  MULTITHREADING: "{{ .Values.gameServer.multithreading }}"
  COMMUNITY: "{{ .Values.gameServer.community.enabled }}"
  PUBLIC_IP: ""
  PUBLIC_PORT: ""
  SERVER_NAME: "{{ regexReplaceAll "\\W+" (default (printf "%s_%s" "palworld" (randAlphaNum 6 | nospace)) .Values.gameServer.serverName) "_" }}"
  SERVER_DESCRIPTION: "{{ .Values.gameServer.serverDescription }}"
  RCON_ENABLED: "{{ .Values.rcon.enabled }}"
  BACKUP_CRON_EXPRESSION: "{{ .Values.gameServer.backup.cron_expression }}"
  BACKUP_ENABLED: "{{ .Values.gameServer.backup.enabled }}"
  DELETE_OLD_BACKUPS: "{{ .Values.gameServer.backup.delete_old_backups }}"
  OLD_BACKUP_DAYS: "{{ .Values.gameServer.backup.old_backup_days | int }}"
  {{- if .Values.gameServer.world_parameters }}
  {{- with .Values.gameServer.world_parameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}