---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palworld-k8s.fullname" . }}
  labels:
    {{- include "palworld-k8s.labels" . | nindent 4 }}
data:
  TZ: "{{ .Values.tz }}"
  PLAYERS: "{{ .Values.gameServer.players | int }}"
  MULTITHREADING: "{{ .Values.gameServer.multithreading }}"
  COMMUNITY: "{{ .Values.gameServer.community.enabled }}"
  PUBLIC_IP: ""
  PUBLIC_PORT: ""
  SERVER_NAME: "{{ regexReplaceAll "\\W+" (default (printf "%s_%s" "palworld" (randAlphaNum 6 | nospace)) .Values.gameServer.serverName) "_" }}"
  SERVER_DESCRIPTION: "{{ .Values.gameServer.serverDescription }}"
  RCON_ENABLED: "{{ .Values.rcon.enabled }}"
