---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld-k8s.fullname" . }}
  labels:
    {{- include "palworld-k8s.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "palworld-k8s.selectorLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "palworld-k8s.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "palworld-k8s.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.gameServer.backup.enabled }}
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - rcon-cli save && backup
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "palworld-k8s.fullname" . }}
          env:
            - name: SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "palworld-k8s.fullname" .) .Values.gameServer.existingSecret | quote }}
                  key: server-password
            {{- if .Values.rcon.enabled }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "palworld-k8s.fullname" .) .Values.rcon.existingSecret | quote }}
                  key: admin-password
            {{- end }}
          ports:
            - name: gameserver
              containerPort: 8211
              protocol: UDP
            - name: queryport
              containerPort: 27015
              protocol: UDP
            - name: rcon
              containerPort: 25575
              protocol: TCP
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - mountPath: /palworld
              name: datadir
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: datadir
          persistentVolumeClaim:
            {{- if not .Values.persistence.existingClaim }}
            claimName: {{ include "palworld-k8s.fullname" . }}
            {{ else }}
            claimName: "{{ .Values.persistence.existingClaim }}"
            {{- end }}
      {{- end }}