{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "palworld-k8s.fullname" . }}
  labels:
    {{- include "palworld-k8s.labels" . | nindent 4 }}
    {{- if .Values.persistence.preventDelete }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
