{{- if or (not .Values.gameServer.existingSecret) (not .Values.rcon.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "palworld-k8s.fullname" . }}
  labels:
    {{- include "palworld-k8s.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not .Values.gameServer.existingSecret }}
  server-password: {{ default (randAlphaNum 12) .Values.gameServer.password | b64enc | quote }}
{{- end}}
{{- if .Values.rcon.enabled }}
{{- if not .Values.rcon.existingSecret }}
  admin-password: {{ default (randAlphaNum 12) .Values.rcon.password | b64enc | quote }}
{{- end}}
{{- end }}
{{- end }}
