---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld-k8s.fullname" . }}
  labels:
    {{- include "palworld-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: gameserver
      port: {{ .Values.gameServer.service.port | int }}
      protocol: UDP
      targetPort: gameserver
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "" .Values.gameServer.service.nodePort | int }}
      {{- end }}
    {{- if .Values.gameServer.community.enabled }}
    - name: queryport
      port: {{ .Values.gameServer.community.service.port | int }}
      protocol: UDP
      targetPort: queryport
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "" .Values.gameServer.community.service.nodePort | int }}
      {{- end }}
    {{- end }}
    {{- if .Values.rcon.enabled }}
    - name: rcon
      port: {{ .Values.rcon.service.port | int }}
      protocol: TCP
      targetPort: rcon
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "" .Values.rcon.service.nodePort | int }}
      {{- end }}
    {{- end }}
  selector: 
    {{- include "palworld-k8s.selectorLabels" . | nindent 4 }}
