# -- Override the name of the chart.
# Default is the chart name.
nameOverride: ""

# -- Override the full name of the chart.
# Default is a combination of release name and chart name.
fullnameOverride: ""

# -- Timezone setting for the server.
tz: "UTC"

image:
  # -- Container registry for the image.
  registry: docker.io
  # -- Image repository
  repository: thijsvanloef/palworld-server-docker
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag.
  # Default is the chart appVersion.
  tag: ""

# -- Update strategy for deployments.
updateStrategy:
  type: Recreate

service: 
  # -- Service type (e.g., LoadBalancer, ClusterIP, NodePort)
  type: LoadBalancer

gameServer:
  # -- Number of players allowed on the server concurrently.
  players: 16
  # -- Enable multithreading.
  multithreading: true
  # -- Custom server name.
  serverName: ""
  # -- Description for the server.
  serverDescription: "" 
  # -- Name of an existing secret for the server password.
  existingSecret: ""
  # -- Server password
  # If one is not provided or an existing secret it not provided, one will be generated.
  password: ""
  service:
    # -- Service port for the game server.
    port: 8211
    # -- (int) Node port for the game server (for NodePort service type).
    nodePort: 
  community:
    # -- Enable if you want your server to show up as a community server.
    enabled: false
    service:
      # -- Service port for a community server.
      port: 27015
      # -- (int) Node port a community server (for NodePort service type).
      nodePort: 
  # -- (object) Configure the game world settings.
  # Use quotes to avoid validation issues.
  # Accepted values are given [here](https://github.com/thijsvanloef/palworld-server-docker/blob/main/.env.example)
  # @notationType -- bigValue
  world_parameters:
    DIFFICULTY: "None"
    DAYTIME_SPEEDRATE: "1.000000"
    NIGHTTIME_SPEEDRATE: "1.000000"
    EXP_RATE: "1.000000"
    PAL_CAPTURE_RATE: "1.000000"
    PAL_SPAWN_NUM_RATE: "1.000000"
    PAL_DAMAGE_RATE_ATTACK: "1.000000"
    PAL_DAMAGE_RATE_DEFENSE: "1.000000"
    PLAYER_DAMAGE_RATE_ATTACK: "1.000000"
    PLAYER_DAMAGE_RATE_DEFENSE: "1.000000"
    PLAYER_STOMACH_DECREASE_RATE: "1.000000"
    PLAYER_STAMINA_DECREASE_RATE: "1.000000"
    PLAYER_AUTO_HP_REGEN_RATE: "1.000000"
    PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP: "1.000000"
    PAL_STOMACH_DECREASE_RATE: "1.000000"
    PAL_STAMINA_DECREASE_RATE: "1.000000"
    PAL_AUTO_HP_REGEN_RATE: "1.000000"
    PAL_AUTO_HP_REGEN_RATE_IN_SLEEP: "1.000000"
    BUILD_OBJECT_DAMAGE_RATE: "1.000000"
    BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: "1.000000"
    COLLECTION_DROP_RATE: "1.000000"
    COLLECTION_OBJECT_HP_RATE: "1.000000"
    COLLECTION_OBJECT_RESPAWN_SPEED_RATE: "1.000000"
    ENEMY_DROP_ITEM_RATE: "1.000000"
    DEATH_PENALTY: "All"
    ENABLE_PLAYER_TO_PLAYER_DAMAGE: "False"
    ENABLE_FRIENDLY_FIRE: "False"
    ENABLE_INVADER_ENEMY: "True"
    ACTIVE_UNKO: "False"
    ENABLE_AIM_ASSIST_PAD: "True"
    ENABLE_AIM_ASSIST_KEYBOARD: "False"
    DROP_ITEM_MAX_NUM: "3000"
    DROP_ITEM_MAX_NUM_UNKO: "100"
    BASE_CAMP_MAX_NUM: "128"
    BASE_CAMP_WORKER_MAXNUM: "15"
    DROP_ITEM_ALIVE_MAX_HOURS: "1.000000"
    AUTO_RESET_GUILD_NO_ONLINE_PLAYERS: "False"
    AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS: "72.00000"
    GUILD_PLAYER_MAX_NUM: "20"
    PAL_EGG_DEFAULT_HATCHING_TIME: "72.00000"
    WORK_SPEED_RATE: "1.000000"
    IS_MULTIPLAY: "False"
    IS_PVP: "False"
    CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: "False"
    ENABLE_NON_LOGIN_PENALTY: "True"
    ENABLE_FAST_TRAVEL: "True"
    IS_START_LOCATION_SELECT_BY_MAP: "True"
    EXIST_PLAYER_AFTER_LOGOUT: "False"
    ENABLE_DEFENSE_OTHER_GUILD_PLAYER: "False"
    COOP_PLAYER_MAX_NUM: "4"
    REGION: ""
    USEAUTH: "True"
    BAN_LIST_URL: "https://api.palworldgame.com/api/banlist.txt"
  backup:
    # -- Enable or disable automatic backups.
    enabled: true
    # -- Cron expression for backup scheduling.
    # Defines when the backups should be triggered. The default value schedules
    # a backup at midnight every day. Use standard cron format.
    cron_expression: "0 0 * * *"
    # -- Flag to decide whether to delete old backups.
    # If set to true, backups older than a specified number of days will be deleted.
    delete_old_backups: false
    # -- The number of days to keep old backups.
    # If `delete_old_backups` is enabled, backups older than this number of days will be deleted.
    old_backup_days: 30
  auto_update:
    # -- Enable or disable automatic updates.
    enabled: false
    # -- Cron expression for updates.
    # Defines when the update check should run. The default value checks for updates every hour.
    # Use standard cron format.
    cron_expression: "0 * * * *"
    # -- Time, in minutes, to send a server message to warn users before an update. 
    warn_minutes: 30
  auto_reboot:
    # -- Enable or disable automatic pod reboots.
    # This feature is to alleviate some issues seen with memory leaks.
    enabled: false
    # -- Cron expression for automatic reboots.
    # Defines when to reboot. The default value schedules a reboot 
    # at midnight every day. Use standard cron format.
    cron_expression: "0 0 * * *"
    # -- Time, in minutes, to send a server message to warn users before a reboot. 
    warn_minutes: 5

# -- Define extra environment variables to pass directly to the container.
# Any env vars which are set by other values will be overridden.
# Useful for defining the env vars for setting up Discord webhooks.
extraEnv: {}

rcon:
  # -- Enable or disable RCON.
  enabled: true
  # -- Name of an existing secret for the RCON (admin) password.
  existingSecret: ""
  # -- RCON (admin) password.
  # If one is not provided and RCON is enabled, one will be generated.
  password: ""
  service:
    # -- Service port for RCON.
    port: 25575
    # -- (int) Node port for RCON (for NodePort service type).
    nodePort: 

persistence:
  # -- Enable or disable persistence.
  enabled: true
  # -- Name of an existing persistentVolumeClaim.
  existingClaim: ""
  # -- Storage class name for the PVC.
  storageClassName: ""
  # -- Access mode for the persistent volume.
  accessMode: ReadWriteOnce
  # -- Prevent Helm from deleting the PVC.
  # Some storageClasses (such as the local-path-provisioner installed by default by k3s) have reclaimPolicy: Delete.
  preventDelete: true
  # -- Size of the persistent volume.
  size: 12Gi

resources:
  # -- Resource limits (CPU, Memory) for the server.
  limits:
    memory: 16Gi
    cpu: 4
  # -- Resource requests (CPU, Memory) for the server.
  requests:
    memory: 8Gi
    cpu: 4

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: false
  # -- Annotations to add to the service account.
  annotations: {}
  # -- The name of the service account.
  name: ""

# -- Node selector for pod scheduling.
nodeSelector: {}

# -- Affinity rules for pod scheduling.
affinity: {}

# -- Tolerations for pod scheduling.
tolerations: {}

# -- Annotations to add to the pod.
podAnnotations: {}

# -- Security context for the pod.
podSecurityContext: {}

# -- Security context for the pod containers.
securityContext: {}
